name: Make Environment Files

on:
  workflow_dispatch:

jobs:
  make-env-files:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Fetch environments
      run: |
        curl -s -f -o response.json --location 'https://api.bricks-dev.com/api/v1/environments?all=true&expand=false&limit=10&offset=0' --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1VUEt1SkE1NlljR3V4RE5rQnJUdCJ9.eyJlbWFpbCI6ImlkYW5AYmx1ZWJyaWNrcy5jbyIsIm9yZ2FuaXphdGlvbiI6ImJsdWVicmlja3MiLCJpc3MiOiJodHRwczovL2F1dGguYnJpY2tzLWRldi5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTAyNzA3NzExNTE0NjQxNzM1MjQiLCJhdWQiOlsiaHR0cHM6Ly9ibHVlYnJpY2tzLWFwaS1kZXYiLCJodHRwczovL2JsdWVicmlja3MtZGV2ZWxvcC5ldS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzMxNDIxNjIzLCJleHAiOjE3MzE1MDgwMjMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJvcmdfaWQiOiJvcmdfZTVPaDFhZXh3NE9VRFptZCIsImF6cCI6ImxFeERXQ045WWZ1cG5MV29aTzBFQWNkODhoMUNrQmpVIiwicGVybWlzc2lvbnMiOlsiY3JlYXRlOmNsb3VkIiwiY3JlYXRlOmRlcGxveW1lbnQiLCJjcmVhdGU6ZW52aXJvbm1lbnQiLCJjcmVhdGU6cGFja2FnZSIsImNyZWF0ZTp1c2VycyIsImRlbGV0ZTpjbG91ZCIsImRlbGV0ZTplbnZpcm9ubWVudCIsImRlbGV0ZTpwYWNrYWdlIiwiZGVsZXRlOnVzZXJzIiwicmVhZDpjbG91ZCIsInJlYWQ6ZGVwbG95bWVudCIsInJlYWQ6ZGVwbG95bWVudC1wbGFuIiwicmVhZDplbnZpcm9ubWVudCIsInJlYWQ6b3JnYW5pemF0aW9uIiwicmVhZDpwYWNrYWdlIiwicmVhZDpyZXNjdWUiLCJyZWFkOnRhc2siLCJyZWFkOnVzZXJzIiwicmVhZDp2ZW5kb3IiLCJyZWFkOndlYmhvb2siLCJ1cGRhdGU6ZGVwbG95bWVudCIsInVwZGF0ZTplbnZpcm9ubWVudCIsInVwZGF0ZTpvcmdhbml6YXRpb24iLCJ1cGRhdGU6cGFja2FnZSIsInVwZGF0ZTp1c2VycyJdfQ.RIUG-QQ06Dpw0yRsUpBa5ygLtqPlPMXKM23InCniFgHW1l2XvV7drnTUnoS2QT5pB3e8Q1cV6x0wC9Iq9TEnN15A86kfYrVK5PiFzzTQl5xUb5yhidekyuqPxgx2W07Lv8o_9S6Nmi1R0FyJ_Dt8qas6aLqvqQunVj_0Js7A0yQjdLuG8R1TbYtfbmmWtWue0sUva5pO5p-lwwwxUHq2g1qQhumGrPG6PQceYHB6hTWOAVDVXu1tCf8e2yxH4xWQ48y3WETMoo0Dfq5mWpmTexBUqDdxad5yfZlz76u2OpYGTHfcMYEHMOWt2ClpyQ2f_VieFrsXu4nIQgwQROE2_A'

    - name: Create new environment files
      run: |
        jq -c '.list[]' response.json | while read -r item; do slug=$(jq -r '.slug' <<< "$item"); jq '{type: "environment"} + .' <<< "$item" > "${slug}.json"; done

    - name: remove temp files
      run: |
        rm response.json

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git status --short | grep '?? .*\.json' | awk '{print $2}' | xargs git add
        git commit -m "Add new files with JSON content"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
